version: '3.8'

services:
  backend:
    image: ghcr.io/sr-distributed-game/backend:${VERSION}
    ports:
      - "8080:8080"

  frontend:
    image: ghcr.io/sr-distributed-game/frontend:${VERSION}
    ports:
      - "4173:4173"